### ISSUE TITLE
Move buildings tab to the left pane

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#23]
I think it would make more sense from users point of view, to have buildings tab in the left pane with groups and templates.

**Comment by MortenTobiasNielsen** [comment]
I think that makes sense. Would it be better to have the Task list to the left and then have the three other views to the rights or is it more intuitive that the task list is to the right?

**Comment by theis999** [comment]
I think having the tasks on the right is perfectly fine.
