### ISSUE TITLE
Goal: Debug

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#24]
It would be nice to have debug / development goal, like any% or steelaxe%. Where additional information is printed in the console for easier understanding of what is going on.

**Comment by MortenTobiasNielsen** [comment]
What level of detail would you like to have? E.g. printing every tick seems a bit excessive.

**Comment by theis999** [comment]
I am not entirely sure yet. I know i want to know which tick an action begins at so i can calculate which tick a smelt or similar is completed.

**Comment by MortenTobiasNielsen** [comment]
That sounds like a good idea.

**Comment by MortenTobiasNielsen** [comment]
This would take a lot of work, but what if you were able to give a command from the tool, which would set a timer for when the next unit is done from a furnace, assembling machine, etc. which would then be shown as an ordered list in game as a GUI element. The timer would need to be able to cycle by itself, so the user doesn't need to constantly set timers. 

This would also be very useful for crafts.

**Comment by theis999** [comment]
It might be easier to write a supporting mod, that prints information on entities relating to their status. Similar to what [Bottleneck](https://mods.factorio.com/mod/Bottleneck)

**Comment by MortenTobiasNielsen** [comment]
I think you are right.
