### ISSUE TITLE
Placement sounds

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#25]
It appears that entities place through the API doesn't generate the usual game sounds.
useful references: 

- https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.play_sound
- https://lua-api.factorio.com/latest/events.html#on_built_entity

also 
_Oh yeah I also thought of that when I was watching some time ago. Also good would be having graphics show when putting/taking items, which should be possible with https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.create_local_flying_text_

**Comment by MortenTobiasNielsen** [comment]
It could require a good amount of work unless the sounds aligns with the normal names of the buildings, in which case it could be done sole by changing the lua script. 

Agreed that would be nice. It should be an option, which can toggled. It might get pretty absurd when doing 60 put/take actions in a second.

**Comment by theis999** [comment]
I am pretty sure the absurdity of fast controls is what people want to experience.
But i agree, i don't think it is as easy as it sounds. We will see

**Comment by MortenTobiasNielsen** [comment]
Now that I think about it, it might not be so bad. I guess the text will be spawned, at the entity where the action is made and not at the player.

**Comment by theis999** [comment]
This is probably related to put and take actions not showing the little white floating text, that usually appears when a player usually does those things.

**Comment by MortenTobiasNielsen** [comment]
I would guess so.

**Comment by theis999** [comment]
Turns out we need to use
https://lua-api.factorio.com/latest/events.html#script_raised_built
https://lua-api.factorio.com/latest/events.html#script_raised_set_tiles

**Comment by MortenTobiasNielsen** [comment]
Do we need to use these events in combination with something or instead of something - the description is pretty cryptic. 😅

**Comment by theis999** [comment]
I am sorry if was cryptic, i just added links for reading. Anyway i actually implemented the play sound in #31 so looking at the code might be more understandable.

I might look at handling tile placement sounds etc later.
