### ISSUE TITLE
Placing tiles crashes the game

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#27]
Placing tiles is currently unhandled and crashes the game. To fix this we need to use [set_tiles](https://lua-api.factorio.com/latest/LuaSurface.html#LuaSurface.set_tiles) in the lua function build()

![image](https://user-images.githubusercontent.com/18309265/188269662-a1ff5bed-c149-4951-86c2-2c58c618aea2.png)

**Comment by MortenTobiasNielsen** [comment]
I tried to solve that when I first developed the tool, but gave up and moved on - Great that you have found a solution for that. 👍
