### ISSUE TITLE
Move Lua strings into new Lua files

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#36]
I think it would be helpful to have most of the lua strings, in lua files.

It would make it easier to copy code from a debug application to the repository.
It would give us better code support.

I use VS code to edit the lua files as it has support for lua code.

**Comment by MortenTobiasNielsen** [comment]
If it can be integrated with the script generation in C++ I don't have an issue with having sperate Lua files. I think I just couldn't figure out a way when I developed the tool - I made control_info, it worked, and I moved on. 😅

**Comment by theis999** [comment]
I imagined that was the reason. It also isn't critical, just a slight annoyance. I'll look at it once all my current changes are merged in.

**Comment by theis999** [comment]
I got my first "string too big" compile error on **control_lua1** today, so this might be more critical than i thought.

**Comment by MortenTobiasNielsen** [comment]
It is luckily relatively simple to solve - split the string into more strings, it isn't pretty but it works. :)

**Comment by theis999** [comment]
Closing this as it is completed
