### ISSUE TITLE
Skip cutscene

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#57]
We can maybe use [this code](https://github.com/ClaudeMetz/UntitledGuiGuide/blob/master/code/chapter-0/UntitledGuiGuide_1.1.0/control.lua) to skip the cutscene.

**Comment by MortenTobiasNielsen** [comment]
Nice. I tried to implement it in the start, but had to give up. I hope this works. :D

**Comment by theis999** [comment]
Someone in team steelaxe (lark maybe) suggested it. I haven't tested it, but it did look promissing

**Comment by MortenTobiasNielsen** [comment]
It unfortunately turns out that this only works when it removes the crash site, which is a little unfortunate.

**Comment by theis999** [comment]
I have noticed the same thing. Which leaves us with two paths forward:

1. Ask for help / changes
2. Recreate the crash site ourselves

**Comment by MortenTobiasNielsen** [comment]
Well if it is easy to recreate the crash site I guess that is the most straight forward, but asking for a change could for sure also be the way to go. I guess we can't be the only once who would like to be able to skip the cutscene and still have the crash site there.

**Comment by theis999** [comment]
Perhaps not, i have created a forum post so we will see.

I also took a look at recreating the crashsite. I wouldn't call it easy, but it was seem doable.

**Comment by theis999** [comment]
On the forums they suggested [NoFreeplayCutscene](https://mods.factorio.com/mod/NoFreeplayCutscene), which does appear to work. So we could just include it as mod dependency.

**Comment by MortenTobiasNielsen** [comment]
It seems like the mod creator thinks that we should just get out acts together. :)
![image](https://user-images.githubusercontent.com/48355480/190111414-7e6051ca-d439-4616-ad83-3a26dba7fe1b.png)

**Comment by theis999** [comment]
Haha, our issue is the cutscene though. 
We don't have any issues with the script breaking due to the player not being created before the end of the cutscene.

**Comment by MortenTobiasNielsen** [comment]
Fair point.

I think I will have a look at what the mod does - if it is super simple I might just copy it, so we don't have to be dependent on a mods which "Ideally shouldn't be necessary".

**Comment by theis999** [comment]
I have already copied most of the mod code into #65

**Comment by MortenTobiasNielsen** [comment]
Closed in #65
