### ISSUE TITLE
Pickup is missing walking

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#58]
As is, the pickup task, runs for 1 tick while you are forced to stand still.

In regular factorio, 
- it is something you can do while walking/mining/shooting etc. 
- it is something you do for awhile

**Comment by MortenTobiasNielsen** [comment]
Yeah that is clearly not intended - good you found it. I haven't had to use pickup or drop while walking, so I haven't run into the problem. I am not entirely sure how this should be implemented.

I guess it pickup could be treated like a walk task, where a specific variable is set to true to indicate that this is both a walk and pickup task.

**Comment by theis999** [comment]
It looks like [picking_state](https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.picking_state) is just a state you set. 
So we could have two tasks: a "begin pick-up", and a "end pick-up" that are both tick-less.

That at least seems like the simplest to me.

**Comment by MortenTobiasNielsen** [comment]
True. I guess it could just be that the pick up task flips the [picking_state](https://lua-api.factorio.com/latest/LuaControl.html#LuaControl.picking_state). So the first pick up task would set it to true and the next to false. That would though create problems with saves, which would not be able to know if there was a pick up task before the save.

**Comment by theis999** [comment]
I guess, 

Alternatively we could have it be part of other tasks, 
Or if we want it to be timed, we could fire a delayed trigger using the lua raise event framework.

**Comment by MortenTobiasNielsen** [comment]
It seems like the code currently just set the picking state to true, and It doesn't seem like it can be set to false again:
![image](https://user-images.githubusercontent.com/48355480/193412320-bb69fb47-dc57-4a94-bd49-067c29abd3c3.png)

I apparently haven't tested the pick_up step enough and I never had to use it in my runs. I can't test it out now, but I would guess that it can be solved by making the pick step slip the current picking_state and removing it from the "cannot be performed while running steps":
![image](https://user-images.githubusercontent.com/48355480/193412556-2967cf2e-ce74-4aa4-b85d-d0f6ab43d6b1.png)

I am a little puzzled about how Zaspar have been able to use pick up, given that it seems like it would just make the player constantly pick up for the rest of the game.

**Comment by theis999** [comment]
Fascinating. I ran it through with a debugger and it appears like the picking_state is reset to false every tick by the game. The user can however set it to true by holding **f**.

I also noticed that Zaspar used the pickup task as walk commands a few times in the beginning.

**Comment by MortenTobiasNielsen** [comment]
I see - that makes sense. I will try to find a solution, where the player can move while picking up.
