### ISSUE TITLE
White flying text is slightly off

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#64]
I have noticed that the text spawns with the center at the center of the target. While in factorio it spawns with left aligned with the targets center.

It also uses the internal name (iron-ore instead of Iron ore)

**Comment by MortenTobiasNielsen** [comment]
I see yeah that is a little irritating, but luckily not really game breaking. :)

**Comment by MortenTobiasNielsen** [comment]
Closed #72
