### ISSUE TITLE
Save / Start is inconsistent

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#87]
It would be most intuitive if you could replace a Save command with a Start command. This however does not always work.

Save runs tickless, that is to say it runs the next command in the same tick. It might however be better if it Save was run as part of the previous command.

**Comment by MortenTobiasNielsen** [comment]
That sounds like a good idea. I have seen some inconsistency where it is trying to do the previous step when the save starts. 

I like to have the flexibility to move the start command around and still have my save commands, It wasn't my intention that the save commands should be removed.

**Comment by theis999** [comment]
It shouldn't matter if you replace or append a start command. Both of these should work:
[a, b, save, d, e] -> [a, b, start, d, e]
[a, b, save, d, e] -> [a, b, save, start, d, e]

**Comment by MortenTobiasNielsen** [comment]
Agreed.

**Comment by theis999** [comment]
#117 Closes this
