### ISSUE TITLE
Refactor: Split step handler

### ISSUE THREAD

**Issue by theis999** [MortenTobiasNielsen/TAS-Helper-for-Factorio#98]
Currently the Main tick handler does:
1. a bit of setup
2. then it checks in order -> last task, pause, stop, speed, save - and performs these tickless
3. then it checks if the character is walking and performs the next task in tick:
- if not walking -> idle, walk, mine, or another standing task
- if walking and the task is not walking, mining, idling or picking -> do task while walking
- or just walk

2 cares a lot about the order of operations, which is odd since they are tickless. So it should not matter if you save first or change speed first.
This order means that we effectively have the setup of => setup, pre-tick, on-tick.
My proposal is to have the setup of => setup, pre-tick, on-tick post-tick.
Where on-tick still handles step 3. 
Pre-tick should be while loop, so the order doesn't matter. 
Post-tick can be used saving the game and composite task.

**Comment by MortenTobiasNielsen** [comment]
Sounds good. As a concept I have no objections, but it could have some unknown consequences when it is actually implemented, given that it most likely is a larger re-write. 

I am not really sure about the while loop - I think I have to see that in code. Won't the while loop block the thread, if it is separate from the main tick handling and does it matter whether these are in order?

**Comment by theis999** [comment]
#117 closes this
